CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "ParentId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Suppliers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "ContactPerson" text NOT NULL,
        "Address" text NOT NULL,
        "Phone" text NOT NULL,
        "Email" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Units" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Symbol" character varying(10) NOT NULL,
        "Type" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Units" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Email" text NOT NULL,
        "Password" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Warehouses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Address" text NOT NULL,
        "Phone" text NOT NULL,
        "Email" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "Capacity" text NOT NULL,
        CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "SKU" character varying(50) NOT NULL,
        "CategoryId" integer NOT NULL,
        "SupplierId" integer NOT NULL,
        "BaseUnitId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Products_Units_BaseUnitId" FOREIGN KEY ("BaseUnitId") REFERENCES "Units" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "Inventories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "ReorderLevel" integer,
        "ReorderQuantity" integer,
        "LastCountedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Inventories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Inventories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "StockMovements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "WarehouseId" integer NOT NULL,
        "MovementType" character varying(10) NOT NULL,
        "Quantity" integer NOT NULL,
        "ReferenceNumber" character varying(50),
        "Reason" character varying(100) NOT NULL,
        "Notes" character varying(500),
        "UserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StockMovements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockMovements_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockMovements_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_StockMovements_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE TABLE "UnitConversions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "FromUnitId" integer NOT NULL,
        "ToUnitId" integer NOT NULL,
        "ConversionFactor" numeric NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_UnitConversions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UnitConversions_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UnitConversions_Units_FromUnitId" FOREIGN KEY ("FromUnitId") REFERENCES "Units" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UnitConversions_Units_ToUnitId" FOREIGN KEY ("ToUnitId") REFERENCES "Units" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_Categories_Name" ON "Categories" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_Categories_ParentId" ON "Categories" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Inventory_ProductId" ON "Inventories" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_Products_BaseUnitId" ON "Products" ("BaseUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Products_SKU" ON "Products" ("SKU");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_Products_SupplierId" ON "Products" ("SupplierId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovement_CreatedAt" ON "StockMovements" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovement_Product_Warehouse_Date" ON "StockMovements" ("ProductId", "WarehouseId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovements_ProductId" ON "StockMovements" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovements_UserId" ON "StockMovements" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovements_WarehouseId" ON "StockMovements" ("WarehouseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_Suppliers_Name" ON "Suppliers" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_UnitConversion_Product_FromTo" ON "UnitConversions" ("ProductId", "FromUnitId", "ToUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_UnitConversions_FromUnitId" ON "UnitConversions" ("FromUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    CREATE INDEX "IX_UnitConversions_ToUnitId" ON "UnitConversions" ("ToUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508170641_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508170641_InitialPostgres', '10.0.7');
    END IF;
END $EF$;
COMMIT;

